### ISSUE TITLE
I have an issue with this

### ISSUE THREAD

**Issue by BlakeGuilloud** [ajmason20/Spaghetti#4]

**Comment by BlakeGuilloud** [comment]
@drtonton 
@ajmason20

**Comment by drtonton** [comment]
@BlakeGuilloud I am closing this issue due to irrelavance

**Comment by BlakeGuilloud** [comment]
@drtonton please leave open for admin review.

**Comment by drtonton** [comment]
@BlakeGuilloud 
![image](https://cloud.githubusercontent.com/assets/16889026/21375734/a4bd5b86-c6fd-11e6-9129-f9481c8c1ed0.png)
